server:
  # 服务器的HTTP端口，默认为8080
  port: 8081
  
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infordata?serverTimezone=UTC
    username: root
    password: Root123$%
  
# 日志配置
logging:
  level:
    root: DEBUG