dataTransfer:
  # 名称
  name: Data Transfer
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2024
  
# 开发环境配置
server:
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

spring:
  profiles:
    active: dev
  application:
    name: dataTransfer
    # 配置Thymeleaf模板
  thymeleaf:
    cache: false                      # 是否有模板缓存
    prefix: classpath:/templates/     # 模板放置的位置
    suffix: .html                     # 模板后缀
    mode: HTML                        # 模板类型
    encoding: UTF-8                   # 模板编码
#swagger 报错解决
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER

# MyBatis配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.dataTransfer.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  # 配置了日志输出信息
  #configLocation: classpath:mybatis/mybatis-config.xml
  
logging:
  pattern:
    dateformat: HH:mm:ss
  file:
    path: logs
  
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api
