package com.dataTransfer.dao;

import com.dataTransfer.model.UserInfo;

public interface UserInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_data
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_data
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	int insert(UserInfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_data
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	int insertSelective(UserInfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_data
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	UserInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_data
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	int updateByPrimaryKeySelective(UserInfo row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_data
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	int updateByPrimaryKey(UserInfo row);
}