package com.dataTransfer.dto;


import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@Schema(title = "用户模型VO", description = "用户模型VO")
public class UserDto {
	public UserDto() {
		
	}
	@Schema(name = "用户ID", description = "用户ID属性", format = "int64", example = "1")
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.user_name
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "用户姓名", description = "用户姓名属性")
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.phone_md5
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "用户加密电话")
	private String phoneMd5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.phone_no
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "用户加密电话")
	private String phoneNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.city
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "用户城市")
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.user_address
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "用户地址")
	private String userAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.house_space
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "用户住房面积")
	private String houseSpace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.measure_time
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "面积测量时间")
	private String measureTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.comment
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "备注")
	private String comment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_data.create_time
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	@Schema(name = "导出状态")
	private Integer export;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_data
	 * @mbg.generated  Thu Jun 13 15:31:15 CST 2024
	 */
	private static final long serialVersionUID = 1L;	

}
